import Link from 'next/link'
import { requireAdmin } from '@/lib/admin'
import { db, getCategories } from '@/lib/db'

export default async function NewPostPage() {
  await requireAdmin()
  const categories = await getCategories()
  const tags = await db.prepare(`SELECT id,name,slug FROM tags ORDER BY name`).all<{id:string;name:string;slug:string}>()
  return <div className="admin-wrap"><div className="admin-shell"><aside className="admin-side"><Link className="brand" href="/admin/">SUHANUR RAHMAN / CMS</Link><nav className="admin-nav"><Link href="/admin/">Dashboard</Link><Link href="/admin/posts/new/">New post</Link><Link href="/admin/taxonomy/">Categories & tags</Link><Link href="/admin/media/">Media</Link><Link href="/admin/comments/">Comments</Link></nav></aside><main className="admin-main"><p className="kicker">Publishing</p><h1 className="serif">New post</h1><form className="admin-form" action="/api/admin/posts" method="post"><input type="hidden" name="intent" value="create" /><div className="form-row"><label>Title<input name="title" required autoFocus /></label><label>Slug<input name="slug" placeholder="auto-generated-from-title" /></label></div><div className="form-row"><label>Categories<select name="categoryIds" multiple size={Math.min(Math.max(categories.length, 4), 8)}>{categories.map((category)=><option key={category.id} value={category.id}>{category.name}</option>)}</select><small className="muted">Hold Ctrl/Cmd to select multiple categories.</small></label><label>Tags<input name="tags" list="tag-suggestions" placeholder="ai, research, technology" /><datalist id="tag-suggestions">{tags.results.map((tag)=><option key={tag.id} value={tag.name} />)}</datalist><small className="muted">Separate tags with commas.</small></label></div><label>Excerpt<textarea name="excerpt" style={{minHeight:100}} /></label><label>Cover image URL<input name="coverImage" placeholder="https://... or /media/..." /></label><label>Content (Markdown)<textarea className="editor" name="content" placeholder="# Your headline\n\nWrite your article here..." required /></label><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><button className="button" name="status" value="DRAFT">Save draft</button><button className="button" name="status" value="PUBLISHED">Publish</button><Link className="meta" href="/admin/">Cancel</Link></div></form></main></div></div>
}
