import Link from 'next/link'
import { requireAdmin } from '@/lib/admin'
import { db, getCategories } from '@/lib/db'

export default async function EditPostPage({ params }: { params: Promise<{ id: string }> }) {
  await requireAdmin()
  const { id } = await params
  const post = await db.prepare(`SELECT id,title,slug,excerpt,content,cover_image AS coverImage,status,category_id AS categoryId FROM posts WHERE id=? LIMIT 1`).bind(id).first<any>()
  if (!post) return <main className="admin-main"><h1 className="serif">Post not found</h1></main>
  const categories = await getCategories()
  const selectedCategories = await db.prepare(`SELECT category_id AS id FROM post_categories WHERE post_id=? ORDER BY category_id`).bind(id).all<{id:string}>()
  const selectedIds = selectedCategories.results.length ? selectedCategories.results.map((item) => item.id) : (post.categoryId ? [post.categoryId] : [])
  const tags = await db.prepare(`SELECT t.name FROM tags t JOIN post_tags pt ON pt.tag_id=t.id WHERE pt.post_id=? ORDER BY t.name`).bind(id).all<{name:string}>()
  const allTags = await db.prepare(`SELECT id,name FROM tags ORDER BY name`).all<{id:string;name:string}>()
  return <div className="admin-wrap"><div className="admin-shell"><aside className="admin-side"><Link className="brand" href="/admin/">SUHANUR RAHMAN / CMS</Link><nav className="admin-nav"><Link href="/admin/">Dashboard</Link><Link href="/admin/posts/new/">New post</Link><Link href="/admin/taxonomy/">Categories & tags</Link><Link href="/admin/media/">Media</Link><Link href="/admin/comments/">Comments</Link><Link href={`/${post.slug}/`}>View article ↗</Link></nav></aside><main className="admin-main"><p className="kicker">Publishing</p><h1 className="serif">Edit post</h1><form className="admin-form" action="/api/admin/posts" method="post"><input type="hidden" name="intent" value="update" /><input type="hidden" name="id" value={post.id} /><div className="form-row"><label>Title<input name="title" defaultValue={post.title} required autoFocus /></label><label>Slug<input name="slug" defaultValue={post.slug} /></label></div><div className="form-row"><label>Categories<select name="categoryIds" multiple size={Math.min(Math.max(categories.length, 4), 8)} defaultValue={selectedIds}>{categories.map((category)=><option key={category.id} value={category.id}>{category.name}</option>)}</select><small className="muted">Hold Ctrl/Cmd to select multiple categories.</small></label><label>Tags<input name="tags" list="tag-suggestions" defaultValue={tags.results.map((t)=>t.name).join(', ')} /><datalist id="tag-suggestions">{allTags.results.map((tag)=><option key={tag.id} value={tag.name} />)}</datalist><small className="muted">Separate tags with commas.</small></label></div><label>Excerpt<textarea name="excerpt" style={{minHeight:100}} defaultValue={post.excerpt || ''} /></label><label>Cover image URL<input name="coverImage" defaultValue={post.coverImage || ''} /></label><label>Content (Markdown)<textarea className="editor" name="content" defaultValue={post.content} required /></label><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><button className="button" name="status" value="DRAFT">Save draft</button><button className="button" name="status" value="PUBLISHED">Publish</button><Link className="meta" href="/admin/">Cancel</Link></div></form><form action="/api/admin/posts" method="post" style={{marginTop:12}}><input type="hidden" name="intent" value="delete" /><input type="hidden" name="id" value={post.id} /><button className="meta" type="submit">Delete post</button></form></main></div></div>
}
