BEGIN TRANSACTION;
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-1','Uncategorized','uncategorized');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-2','ব্লগিং','blogging');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-3','লার্ন উইদ ডিজিটাল','learn-with-digital');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-4','মার্কেটিং','marketing');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-5','সোশ্যাল মিডিয়া','social-media');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-6','ট্রেন্ডস্‌','trends');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-16','কম্পিউটার প্রোগ্রামিং','computer-programming');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-17','প্রযুক্তি কথন','tech-gossip');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-18','পাইথন','python');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-19','ডেটা সায়েন্স','data-science');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-20','রিসার্চ টুলস','%e0%a6%b0%e0%a6%bf%e0%a6%b8%e0%a6%be%e0%a6%b0%e0%a7%8d%e0%a6%9a-%e0%a6%9f%e0%a7%81%e0%a6%b2%e0%a6%b8');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-21','কোবো টুলবক্স (Kobo Toolbox)','kobo-toolbox');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-22','স্ট্যাটা (STATA)','%e0%a6%b8%e0%a7%8d%e0%a6%9f%e0%a7%8d%e0%a6%af%e0%a6%be%e0%a6%9f%e0%a6%be-stata');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-26','বিবিধ','miscellaneous');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-27','কবিতা','poetry');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-40','স্কিল ডেভেলপমেন্ট ট্রেনিং','skill-development-training');
INSERT OR IGNORE INTO categories (id,name,slug) VALUES ('wp-cat-41','Digital Literacy','digital-literacy');
INSERT OR IGNORE INTO tags (id,name,slug) VALUES ('wp-tag-7','What is Backlink','what-is-backlink');
INSERT OR IGNORE INTO tags (id,name,slug) VALUES ('wp-tag-8','ব্যাকলিংক','%e0%a6%ac%e0%a7%8d%e0%a6%af%e0%a6%be%e0%a6%95%e0%a6%b2%e0%a6%bf%e0%a6%82%e0%a6%95');
INSERT OR IGNORE INTO tags (id,name,slug) VALUES ('wp-tag-9','ব্যাকলিংক কি','%e0%a6%ac%e0%a7%8d%e0%a6%af%e0%a6%be%e0%a6%95%e0%a6%b2%e0%a6%bf%e0%a6%82%e0%a6%95-%e0%a6%95%e0%a6%bf');
INSERT OR IGNORE INTO tags (id,name,slug) VALUES ('wp-tag-24','dailyprompt','dailyprompt');
INSERT OR IGNORE INTO tags (id,name,slug) VALUES ('wp-tag-25','dailyprompt-2097','dailyprompt-2097');
INSERT OR IGNORE INTO tags (id,name,slug) VALUES ('wp-tag-38','dailyprompt-1808','dailyprompt-1808');
INSERT OR IGNORE INTO tags (id,name,slug) VALUES ('wp-tag-39','dailyprompt-1809','dailyprompt-1809');
INSERT OR IGNORE INTO tags (id,name,slug) VALUES ('wp-tag-47','dailyprompt-1986','dailyprompt-1986');
COMMIT;
