'use client'
import { useEffect,useMemo,useRef,useState } from 'react'
import { marked } from 'marked'
type Category={id:string;name:string}; type Tag={id:string;name:string}; type Initial={id?:string;title?:string;slug?:string;excerpt?:string|null;content?:string;coverImage?:string|null;categoryIds?:string[];tags?:string[];seoTitle?:string|null;seoDescription?:string|null;seoKeywords?:string|null;ogImage?:string|null;canonicalUrl?:string|null;noindex?:number}
function wrap(v:string,s:number,e:number,b:string,a=b){return v.slice(0,s)+b+v.slice(s,e)+a+v.slice(e)}
export default function PostEditor({categories,tags,initial={}}:{categories:Category[];tags:Tag[];initial?:Initial}){
 const [content,setContent]=useState(initial.content||''),[preview,setPreview]=useState(false),[mediaOpen,setMediaOpen]=useState(false),[media,setMedia]=useState<any[]>([]),[uploading,setUploading]=useState(false),[dirty,setDirty]=useState(false),[cover,setCover]=useState(initial.coverImage||''); const ref=useRef<HTMLTextAreaElement>(null); const key=useMemo(()=>`blog-draft:${initial.id||'new'}`,[initial.id])
 useEffect(()=>{const s=window.localStorage.getItem(key);if(s)setContent(s)},[key]); useEffect(()=>{if(!content)return;const t=setTimeout(()=>window.localStorage.setItem(key,content),1200);return()=>clearTimeout(t)},[key,content])
 function edit(fn:(v:string,s:number,e:number)=>string){const el=ref.current;if(!el)return;const n=fn(content,el.selectionStart,el.selectionEnd);setContent(n);setDirty(true);requestAnimationFrame(()=>el.focus())}
 function cmd(t:string){edit((v,s,e)=>{const x=v.slice(s,e)||'text';if(t==='h2')return v.slice(0,s)+`## ${x}`+v.slice(e);if(t==='h3')return v.slice(0,s)+`### ${x}`+v.slice(e);if(t==='b')return wrap(v,s,e,'**');if(t==='i')return wrap(v,s,e,'_');if(t==='q')return v.slice(0,s)+`> ${x}`+v.slice(e);if(t==='c')return wrap(v,s,e,'`');if(t==='l')return v.slice(0,s)+`[${x}](https://)`+v.slice(e);if(t==='ul')return v.slice(0,s)+x.split('\n').map(y=>`- ${y}`).join('\n')+v.slice(e);return v.slice(0,s)+x.split('\n').map((y,i)=>`${i+1}. ${y}`).join('\n')+v.slice(e)})}
 async function loadMedia(){setMediaOpen(true);const r=await fetch('/api/admin/media');if(r.ok)setMedia((await r.json()).media||[])}
 async function upload(file:File,insert:boolean){setUploading(true);try{const f=new FormData();f.append('file',file);const r=await fetch('/api/admin/media',{method:'POST',body:f});const d=await r.json();if(!r.ok)throw new Error(d.error||'Upload failed');if(insert)edit((v,s,e)=>v.slice(0,s)+`![${file.name}](${d.url})`+v.slice(e));else setCover(d.url);await loadMedia()}finally{setUploading(false)}}
 return <form className="admin-form post-editor" action="/api/admin/posts" method="post" onSubmit={()=>window.localStorage.removeItem(key)}><input type="hidden" name="intent" value={initial.id?'update':'create'}/>{initial.id&&<input type="hidden" name="id" value={initial.id}/>}<input type="hidden" name="coverImage" value={cover}/>
 <div className="editor-topbar"><div><span className="meta">Publishing</span><span className="autosave">{dirty?'Unsaved changes':'Local autosave enabled'}</span></div><div><button type="button" className={preview?'meta':'button'} onClick={()=>setPreview(false)}>Write</button> <button type="button" className={preview?'button':'meta'} onClick={()=>setPreview(true)}>Preview</button></div></div>
 <div className="form-row"><label>Title<input name="title" defaultValue={initial.title} required autoFocus/></label><label>Slug<input name="slug" defaultValue={initial.slug}/></label></div><div className="form-row"><label>Categories<select name="categoryIds" multiple size={Math.min(Math.max(categories.length,4),8)} defaultValue={initial.categoryIds||[]}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Tags<input name="tags" defaultValue={(initial.tags||[]).join(', ')} list="tag-suggestions"/><datalist id="tag-suggestions">{tags.map(t=><option key={t.id} value={t.name}/>)}</datalist></label></div>
 <label>Excerpt<textarea name="excerpt" defaultValue={initial.excerpt||''} maxLength={500}/></label><div className="editor-layout"><section className="editor-main"><div className="editor-toolbar">{[['h2','H2'],['h3','H3'],['b','B'],['i','I'],['q','Quote'],['c','Code'],['l','Link'],['ul','• List'],['ol','1. List']].map(([a,b])=><button type="button" key={a} onClick={()=>cmd(a)}>{b}</button>)}<button type="button" onClick={loadMedia}>Media</button><label className="toolbar-upload">Upload image<input type="file" hidden accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f,true)}}/></label></div>{preview?<div className="editor-preview prose" dangerouslySetInnerHTML={{__html:marked.parse(content||'*Nothing to preview*') as string}}/>:<textarea ref={ref} className="editor" name="content" value={content} onChange={e=>{setContent(e.target.value);setDirty(true)}} required/>}</section><aside className="editor-sidebar"><div className="panel"><h3>Featured image</h3><CoverInput value={cover} onChange={setCover} onUpload={f=>upload(f,false)} uploading={uploading}/></div><div className="panel"><h3>SEO</h3><label>SEO title<input name="seoTitle" defaultValue={initial.seoTitle||''} maxLength={60}/></label><label>Meta description<textarea name="seoDescription" defaultValue={initial.seoDescription||''} maxLength={160}/></label><label>Keywords<input name="seoKeywords" defaultValue={initial.seoKeywords||''}/></label><label>Canonical URL<input name="canonicalUrl" defaultValue={initial.canonicalUrl||''}/></label><label>OG image<input name="ogImage" defaultValue={initial.ogImage||''}/></label><label className="check"><input type="checkbox" name="noindex" value="1" defaultChecked={initial.noindex===1}/> Prevent indexing</label></div></aside></div>
 <div className="editor-actions"><div><button className="button" name="status" value="DRAFT">Save draft</button> <button className="button" name="status" value="PUBLISHED">Publish</button>{initial.id&&<button className="danger-button" name="intent" value="trash" formNoValidate>Move to Trash</button>}</div><span className="muted">{uploading?'Uploading…':'Markdown + live preview + image library + autosave'}</span></div>
 {mediaOpen&&<div className="media-modal"><div className="media-dialog"><div className="editor-topbar"><h3>Media library</h3><button type="button" className="meta" onClick={()=>setMediaOpen(false)}>Close</button></div><div className="media-grid">{media.length?media.map(x=><button className="media-card" type="button" key={x.id} onClick={()=>{edit(v=>v+`![Image](${x.url})`);setMediaOpen(false)}}><img src={x.url} alt=""/><span>{x.filename||'Image'}</span></button>):<p className="muted">Upload an image first.</p>}</div></div></div>}</form>
}
function CoverInput({value,onChange,onUpload,uploading}:{value:string;onChange:(v:string)=>void;onUpload:(f:File)=>void;uploading:boolean}){return <div className="cover-picker"><div className="cover-preview">{value?<img src={value} alt=""/>:<span>No featured image</span>}</div><input value={value} onChange={e=>onChange(e.target.value)} placeholder="Paste image URL"/><label className="button small">{uploading?'Uploading…':'Upload image'}<input type="file" hidden accept="image/*" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)onUpload(f)}}/></label></div>}
